### ISSUE TITLE
Local playback does not work on arm

### ISSUE THREAD

**Issue by marecabo** [Ulrar/hassio-addons#1]
When selecting `Built-in Audio Stereo` as output in the addon configuration, local playback (speaker: "Computer") does not work and fails with these messages in the log:

## Addon Audio Config
![image](https://user-images.githubusercontent.com/23156476/83950145-afcfa280-a828-11ea-975f-8ff93ef42089.png)

## Log on RPi3B+ 32bit (`armv7`)
```
[  LOG]   laudio: Cannot open shared library /usr/lib/arm-linux-gnueabihf/alsa-lib/libasound_module_ctl_pulse.so ((null): /usr/lib/arm-linux-gnueabihf/alsa-lib/libasound_module_ctl_pulse.so: cannot open shared object file: No such file or directory)
[  LOG]   laudio: Failed to attach mixer 'default': No such device or address
[  LOG]   laudio: Could not open mixer 'default' ('(null)')
```

## Log on RPi4B 64bit (`aarch64`)
```
[  LOG]   laudio: Cannot open shared library /usr/lib/aarch64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so ((null): /usr/lib/aarch64-linux-gnu/alsa-lib/libasound_module_ctl_pulse.so: cannot open shared object file: No such file or directory)
[  LOG]   laudio: Failed to attach mixer 'default': No such device or address
[  LOG]   laudio: Could not open mixer 'default' ('(null)')
```

**Comment by marecabo** [comment]
Fortunately this can be fixed by adding `libasound2-plugins` to `RUN_DEPS` in the Dockerfile on both of these platforms.

**Comment by Ulrar** [comment]
Ah sorry, I should have specified that you need to use "pulseaudio" as the backend for local, not alsa.
Can you try and confirm it does work ? libasound2-plugins has a plugin to redirect alsa output to pulseaudio, which is why it solves it too.

```
audio {
...
	type = "pulseaudio"
...
}
```

If it works fine for you I'll add a note to the readme

**Comment by marecabo** [comment]
Thanks for this clarification! I just rebuilt the addon without `libasound2-plugins` and can confirm that applying your change in `/share/forked-daapd/forked-daapd.conf` makes it work.

**Comment by Ulrar** [comment]
Great, thanks for the confirmation !
