### ISSUE TITLE
Maybe add a license?

### ISSUE THREAD

**Issue by marecabo** [Ulrar/hassio-addons#13]
Would you mind adding a license to this project? For another project I recently learned, that it can have disadvantages of not having a license for one's open source projects, see https://choosealicense.com/no-permission.

The MIT License seems to be widely used for Hassio add-ons so it would be the first I'd suggest. Also the forked-daapd addon from johnpdowling is licensed under it as well.

You can find boilerplate license templates here: https://choosealicense.com/licenses

**Comment by Ulrar** [comment]
That's a good suggestion. I usually go with the BSD license but that seems to be pretty much the same thing, so let's go with MIT.
Thanks !
