### ISSUE TITLE
does not work with home assistant integration

### ISSUE THREAD

**Issue by nichtmax** [Ulrar/hassio-addons#16]
```
[  LOG]    httpd: Web interface request to '/api/config' denied: No password set in the config
[2020-07-19 21:50:01] [  LOG]    httpd: Web interface request to '/api/config' denied: No password set in the config
```

I tried `localhost`, hostname, docker ip, nothing works. I don't have the problem with https://github.com/Ulrar/hassio-addons so I'm pretty sure it's something in the nginx config.

**Comment by Ulrar** [comment]
Hi,

You're mentioning nginx so I'm assuming this is about forked-daapd ?
Anything unusual about your config, are you using something in front of your instance (other nginx, apache, HAProxy ..), some custom paths or ports, or nabu casa ?

**Comment by Ulrar** [comment]
Hi,

Do you still have an issue with this, or can this be closed ?

**Comment by Ulrar** [comment]
Closing since hasn't been updated in months, feel free to re-open if needed.
