### ISSUE TITLE
Lag Issue, possibly related to this error?

### ISSUE THREAD

**Issue by floodwayprintco** [Ulrar/hassio-addons#19]
I am getting this error a ton in my Raspotify logs. Forked-Daapd is also reporting that it's not getting sufficient data.

`[2020-09-16T14:37:51Z WARN  libmdns::fsm] couldn't parse packet from V4(172.30.32.1:5353): type 47 is invalid`

It's in there a LOT. 

Any suggestions?

**Comment by Ulrar** [comment]
Hi,

Note that I'm not the developer of either projects, I just packaged them into addons. Also raspotify actually hasn't anything to do with raspotify anymore, the addon is compiling librespot from scratch and adding an extra patch to get a metadatapipe.
I see that they updated the mdns library last month for [their issue 520](https://github.com/librespot-org/librespot/issues/520), if you installed the adding before that you could try to uninstall it and re-install it, see if that new version helps.
But I doubt it, mdns should I think only be used to discover devices, not for streaming, it's likely unrelated.

**Comment by floodwayprintco** [comment]
Thank you! Yes I was a bit confused about the duplicated naming. I moved
this onto a dedicated Pi instead of as a Hassio add-on and it works
perfectly with no lag.

--

Cory Beal

*Production Manager @ Floodway Print Company LTD. *

http://floodwayprintco.co <http://floodwayprintco.com/>m

**Comment by Ulrar** [comment]
Good to hear ! Closing this then, thanks.
