### ISSUE TITLE
Forked-daapd not Connecting to Spotify Account

### ISSUE THREAD

**Issue by rml1111** [Ulrar/hassio-addons#20]
I have forked-daapd installed and running. In forked-daapd settings, it appears that I successfully connected to my Spotify Premium account, however, when perform a search in forked-daapd no Spotify results are returned. I have tried to connect via Spotify Web API in forked-daapd settings, however, when I click on the Authorize Web API button, nothing happens. I checked the logs and am seeing multiple messages that "No Spotify refresh token was found".

**Comment by Ulrar** [comment]
Hi,

Sounds like an issue with forked-daapd itself more than with the addon, you might want to get in touch with the project.
I'm myself using aarch64 where libspotify isn't available so I can't test it, but when I was using arm it did work fine. Maybe your adblock blocking a popup ?

**Comment by Ulrar** [comment]
Hey,

Any update on this, are you still having an issue or can this be closed ?
