### ISSUE TITLE
Forked-daapd: 502 Bad Gateway 

### ISSUE THREAD

**Issue by Plobli** [Ulrar/hassio-addons#23]
Hey, I installed the forked-daapd in HA but I can't open the WebUI over http://homeassistant.local:8123/e4ac757a_forked-daapd or connect over the integration. I get only a 502: Bad Gateway.
In the supervisor log I found this issues:

```
21-02-14 11:07:30 ERROR (MainThread) [supervisor.api.security] Invalid token for access /host/info
21-02-14 11:09:32 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-02-14 11:09:36 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.32.1:1337 ssl:default [Connect call failed ('172.30.32.1', 1337
```
What can I do?

**Comment by Ulrar** [comment]
Hi,

Unfortunately that's because of issue #22, which I haven't managed to fix yet.
