### ISSUE TITLE
Cannot Install Forked-DAAPD add-on

### ISSUE THREAD

**Issue by 400HPMustang** [Ulrar/hassio-addons#27]
Home Assistant : core-2021.5.3
Home Assistant OS 5.13

This is the error that shows up when I try to install the add-on

`The command '/bin/bash -o pipefail -c sed -i -e 's/\(uid.*=.*\)/uid = "root"/g' forked-daapd.conf && sed -i s#"ipv6 = yes"#"ipv6 = no"#g forked-daapd.conf && sed -i s#/srv/music#/share/forked-daapd/music#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/songs3.db#/share/forked-daapd/cache/songs3.db#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/cache.db#/share/forked-daapd/cache/cache.db#g forked-daapd.conf && sed -i s#/usr/local/var/log/forked-daapd.log#/dev/stdout#g forked-daapd.conf && sed -i "/websocket_port\ =/ s/# *//" forked-daapd.conf && sed -i "/trusted_networks\ =/ s/# *//" forked-daapd.conf && sed -i "/pipe_autostart\ =/ s/# *//" forked-daapd.conf && sed -i "/db_path\ =/ s/# *//" forked-daapd.conf && sed -i "/cache_path\ =/ s/# *//" forked-daapd.conf && sed -i "/airplay_shared/ s/# *//" forked-daapd.conf && sed -i "/control_port\ =/ s/#/ /" forked-daapd.conf && sed -i "/timing_port\ =/ s/#/ /" forked-daapd.conf && sed -i "/timing_port/{N;s/\n#/\n/}" forked-daapd.conf && sed -i "s/\(control_port =\).*/\1 3690/" forked-daapd.conf && sed -i "s/\(timing_port =\).*/\1 3691/" forked-daapd.conf && sed -i "/type\ =/ s/#/ /" forked-daapd.conf && sed -i 's/\(type =\).*/\1 "pulseaudio"/' forked-daapd.conf' returned a non-zero code: 2`

This is what was in the supervisor logs

```
---> 1007b394157a
Step 10/34 : FROM base AS builder
 ---> 1007b394157a
Step 11/34 : ARG BUILD_ARCH
 ---> Using cache
 ---> ce65e2d662a0
Step 12/34 : RUN mkdir -p /usr/share/man/man1
 ---> Using cache
 ---> b7211f189bbe
Step 13/34 : RUN apt-get update -y && apt-get install -y --no-install-recommends     ${BUILD_DEPS}     && if [ ! "$BUILD_ARCH" = "aarch64" ] ; then         apt-get install -y --no-install-recommends         ${BUILD_DEPS_NO_AARCH64};     fi     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> e029df27d8ce
Step 14/34 : RUN curl -L -o /tmp/antlr-3.4-complete.jar http://www.antlr3.org/download/antlr-3.4-complete.jar     && echo '#!/bin/bash' > /usr/local/bin/antlr3     && echo 'exec java -cp /tmp/antlr-3.4-complete.jar org.antlr.Tool "$@"' >> /usr/local/bin/antlr3     && chmod 775 /usr/local/bin/antlr3
 ---> Using cache
 ---> 3c240db506be
Step 15/34 : WORKDIR /tmp/forked-daapd
 ---> Using cache
 ---> a302120013c6
Step 16/34 : RUN git clone --depth 1 https://github.com/ejurgensen/forked-daapd.git .     && autoreconf -fi     && if [ ! "$BUILD_ARCH" = "aarch64" ] ; then         ./configure         --enable-itunes         --enable-chromecast         --with-pulseaudio         --enable-spotify         --with-libwebsockets;     else         ./configure         --enable-itunes         --enable-chromecast         --with-pulseaudio         --with-libwebsockets;     fi     && make 	&& make install DESTDIR=/tmp/forked-daapd-install
 ---> Using cache
 ---> 339bca95d7c1
Step 17/34 : FROM base AS runner
 ---> 1007b394157a
Step 18/34 : ARG BUILD_ARCH
 ---> Using cache
 ---> ce65e2d662a0
Step 19/34 : COPY --from=builder /tmp/forked-daapd-install /
 ---> Using cache
 ---> ddf7c2cabb7c
Step 20/34 : RUN apt-get update -y && apt-get install -y --no-install-recommends     ${RUN_DEPS} nginx     && if [ ! "$BUILD_ARCH" = "aarch64" ] ; then         apt-get install -y --no-install-recommends         ${RUN_DEPS_NO_AARCH64};     fi     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 0af304cffff7
Step 21/34 : WORKDIR /usr/local/etc
 ---> Using cache
 ---> ba6d4b5b9ca7
Step 22/34 : RUN sed -i -e 's/\(uid.*=.*\)/uid = "root"/g' forked-daapd.conf     && sed -i s#"ipv6 = yes"#"ipv6 = no"#g forked-daapd.conf     && sed -i s#/srv/music#/share/forked-daapd/music#g forked-daapd.conf     && sed -i s#/usr/local/var/cache/forked-daapd/songs3.db#/share/forked-daapd/cache/songs3.db#g forked-daapd.conf     && sed -i s#/usr/local/var/cache/forked-daapd/cache.db#/share/forked-daapd/cache/cache.db#g forked-daapd.conf     && sed -i s#/usr/local/var/log/forked-daapd.log#/dev/stdout#g forked-daapd.conf     && sed -i "/websocket_port\ =/ s/# *//" forked-daapd.conf     && sed -i "/trusted_networks\ =/ s/# *//" forked-daapd.conf     && sed -i "/pipe_autostart\ =/ s/# *//" forked-daapd.conf     && sed -i "/db_path\ =/ s/# *//" forked-daapd.conf     && sed -i "/cache_path\ =/ s/# *//" forked-daapd.conf     && sed -i "/airplay_shared/ s/# *//" forked-daapd.conf     && sed -i "/control_port\ =/ s/#/ /" forked-daapd.conf     && sed -i "/timing_port\ =/ s/#/ /" forked-daapd.conf     && sed -i "/timing_port/{N;s/\n#/\n/}" forked-daapd.conf     && sed -i "s/\(control_port =\).*/\1 3690/" forked-daapd.conf     && sed -i "s/\(timing_port =\).*/\1 3691/" forked-daapd.conf     && sed -i "/type\ =/ s/#/ /" forked-daapd.conf     && sed -i 's/\(type =\).*/\1 "pulseaudio"/' forked-daapd.conf
 ---> Running in 07c37defa2ae
sed: can't read forked-daapd.conf: No such file or directory

Removing intermediate container 07c37defa2ae
```

**Comment by mrachm** [comment]
Same Problem here.
` The command '/bin/bash -o pipefail -c sed -i -e 's/\(uid.*=.*\)/uid = "root"/g' forked-daapd.conf && sed -i s#"ipv6 = yes"#"ipv6 = no"#g forked-daapd.conf && sed -i s#/srv/music#/share/forked-daapd/music#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/songs3.db#/share/forked-daapd/cache/songs3.db#g forked-daapd.conf && sed -i s#/usr/local/var/cache/forked-daapd/cache.db#/share/forked-daapd/cache/cache.db#g forked-daapd.conf && sed -i s#/usr/local/var/log/forked-daapd.log#/dev/stdout#g forked-daapd.conf && sed -i "/websocket_port\ =/ s/# *//" forked-daapd.conf && sed -i "/trusted_networks\ =/ s/# *//" forked-daapd.conf && sed -i "/pipe_autostart\ =/ s/# *//" forked-daapd.conf && sed -i "/db_path\ =/ s/# *//" forked-daapd.conf && sed -i "/cache_path\ =/ s/# *//" forked-daapd.conf && sed -i "/airplay_shared/ s/# *//" forked-daapd.conf && sed -i "/control_port\ =/ s/#/ /" forked-daapd.conf && sed -i "/timing_port\ =/ s/#/ /" forked-daapd.conf && sed -i "/timing_port/{N;s/\n#/\n/}" forked-daapd.conf && sed -i "s/\(control_port =\).*/\1 3690/" forked-daapd.conf && sed -i "s/\(timing_port =\).*/\1 3691/" forked-daapd.conf && sed -i "/type\ =/ s/#/ /" forked-daapd.conf && sed -i 's/\(type =\).*/\1 "pulseaudio"/' forked-daapd.conf' returned a non-zero code: 2 `

## System Health

version | core-2021.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 5.10.17-v8
arch | aarch64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4905
Installed Version | 1.13.2
Stage | running
Available Repositories | 847
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.6
disk_total | 28.6 GB
disk_used | 8.6 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.0.1), Visual Studio Code (3.4.1), Samba share (9.5.1), File editor (5.3.2), Terminal & SSH (9.1.3), Node-RED (9.1.4), Home Assistant Google Drive Backup (0.104.3), Spotify Connect (0.9.0), Zigbee2mqtt (1.20.0-1), RPC Shutdown (2.2), AdGuard Home (4.1.6)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 1
views | 4
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

Any Solution?
